services:
  mongo:
    image: mongo:6.0.5
    ports:
      - "27018:27017"
    env_file:
      - ./.env
    volumes:
      - ./mongodbData:/data/db
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME={MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD={MONGO_INITDB_ROOT_PASSWORD}

  express-api:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
