services:
  express-api:
    build:
      context: .
    container_name: otc-express-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    environment:
      - $SERVICE_FDQN_EXPRESS-API_3000

  mongo:
    image: mongo:6.0.5
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    env_file:
      - ./.env
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - ./.env
    ports:
      - 8081:3000
    environment:
      - $SERVICE_FDQN_MONGO-EXPRESS_8081

volumes:
  mongo-data:
    name: mongo-data
