services:
  express-api:
    build:
      context: .
    container_name: otc-express-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env

  mongo:
    image: mongo:6.0.5
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    env_file:
      - ./.env
    volumes:
      - mongo-data:/data/db

  mongoexpress:
    build:
      context: ./mongoexpress
    container_name: mongoexpress
    restart: always
    env_file:
      - ./.env
    ports:
      - 8081:8081
    environment:
      - SERVICE_FQDN_MONGOEXPRESS
      - PORT=8081

  mcp-server:
    build:
      context: https://github.com/feliceforgione/mcp_server_streamable.git
      dockerfile: Dockerfile
      args:
        PORT: ${MCP_SERVER_PORT}
    container_name: mcp-server
    ports:
      - "${MCP_SERVER_PORT}:${MCP_SERVER_PORT}"
    environment:
      - PORT=${MCP_SERVER_PORT}
      - SERVER_IP=${MCP_SERVER_IP}
      - API_SERVER_TOOLS=${MCP_API_SERVER_TOOLS}

volumes:
  mongo-data:
    name: mongo-data
