services:
  mongo:
    image: mongo:6.0.5
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    env_file:
      - ./.env
    volumes:
      - mongo-data:/data/db

  express-api:
    build:
      context: .
    container_name: otc-express-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env

volumes:
  mongo-data:
    name: mongo-data
