services:
  express-api:
    build:
      context: .
    container_name: otc-express-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env

  mongo:
    image: mongo:6.0.5
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    env_file:
      - ./.env
    volumes:
      - mongo-data:/data/db

  mongoexpress:
    build:
      context: ./mongoexpress
    restart: always
    env_file:
      - ./.env
    ports:
      - 8081:8081
    environment:
      - SERVICE_FQDN_MONGOEXPRESS
      - PORT=8081

volumes:
  mongo-data:
    name: mongo-data
