services:
  express-api:
    build:
      context: .
    container_name: otc-express-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    labels:
      - "traefik.http.routers.express-api.rule=Host(`otc-api.forgeai.dev`)"
      - "traefik.http.services.express-api.loadbalancer.server.port=${PORT}"

  mongo:
    image: mongo:6.0.5
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    env_file:
      - ./.env
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - ./.env
    ports:
      - 8081:3000
    labels:
      - "traefik.http.routers.mongo-express.rule=Host(`otc-api-express.forgeai.dev`)"
      - "traefik.http.services.mongo-express.loadbalancer.server.port=3000"

volumes:
  mongo-data:
    name: mongo-data
