services:
  mongo:
    volumes:
      - ./mongodbData:/data/db
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
    restart: on-failure
